name: Go

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.27.x'

    - name: Run
      env:
        USER: ${{secrets.USER}}
        PASSWORD: ${{secrets.PASSWORD}}
        RECIPIENTS: ${{vars.RECIPIENTS}}
        LOCATION: ${{vars.LOCATION}}
        HEIGHT_TRIGGER: ${{vars.HEIGHT_TRIGGER}}
      run: go run .